[package]
name = "rb"
version = "0.1.0"
authors = ["Nikita Dobrynin / girvel <widauka@ya.ru>"]
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
dirs = "1.0.4"
names = { version = "0.12.0", default-features = false }
